# Generated by Django 5.1.3 on 2025-01-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Périphérique', 'Périphérique')], max_length=50)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('En réparation', 'En réparation'), ('Obsolète', 'Obsolète')], default='Disponible', max_length=50)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etage', models.CharField(blank=True, max_length=50, null=True)),
                ('batiment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('description', models.TextField()),
                ('technicien', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Réparé', 'Réparé'), ('Non réparé', 'Non réparé')], default='Réparé', max_length=50)),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='parc_informatique.appareil')),
            ],
        ),
        migrations.AddField(
            model_name='appareil',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appareils', to='parc_informatique.local'),
        ),
        migrations.AddField(
            model_name='appareil',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appareils', to='parc_informatique.utilisateur'),
        ),
    ]
