# Generated by Django 5.1.5 on 2025-01-25 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parc_informatique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("en cours", "En cours"), ("terminée", "Terminée")],
                        default="en cours",
                        max_length=20,
                    ),
                ),
                (
                    "appareil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envoyer_maintenances",
                        to="parc_informatique.appareil",
                    ),
                ),
            ],
        ),
    ]
