# Generated by Django 5.1.5 on 2025-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parc_informatique", "0002_maintenance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Maintenance",
        ),
    ]
